version: "3.3"
services:
  demo_app:
    build:
      context: src
    ports:
      - "8000:8000"
    restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  prometheus-data:
  grafana-storage:
